services:
  postgres:
    image: postgres:16
    container_name: velostar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: velostar_lakehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d velostar_lakehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-postgres:
    image: postgres:16
    container_name: velostar_airflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: velostar_airflow_init
    restart: "no"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: velostar-airflow-secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PYTHONPATH: /opt/project:/opt/project/src
    depends_on:
      postgres:
        condition: service_healthy
      airflow-postgres:
        condition: service_healthy
    volumes:
      - .:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Velostar
      --lastname Admin
      --role Admin
      --email admin@example.com || true
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: velostar_airflow_webserver
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: velostar-airflow-secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PYTHONPATH: /opt/project:/opt/project/src
    depends_on:
      postgres:
        condition: service_healthy
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: velostar_airflow_scheduler
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: velostar-airflow-secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PYTHONPATH: /opt/project:/opt/project/src
    depends_on:
      postgres:
        condition: service_healthy
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - .:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

volumes:
  postgres_data:
  airflow_postgres_data:
